version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  node-app:
    build: ./app
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
      MONGO_HOST: mongo
      REDIS_HOST: redis
    depends_on:
      - postgres
      - mongo
      - redis